### PR TITLE
Add  xhr progress reporting on upload.

### PR DESCRIPTION
**Pull request by jasonm23**
Set `options.uploadProgress` to 

```
function(progress){ /* var percent = progress * 100; /* }
```

### CODE REVIEW

**Comment by jasonm23** [comment]
@dominicwong617 @rpbaltazar - open for review. add to approve :+1:

**Comment by jasonm23** [comment]
upload-progress

**Comment by rpbaltazar** [comment]
Good for me! :+1:

**Comment by jasonm23** [comment]
Jude and Dom also :+1: ... <sub>apparently</sub>

**Pull request merged**
